// Generated by 'npx gql-gen -s https://graphql-pokeapi.graphcdn.app/ -o ./examples/pokemon.ts -t -c "JSON: object" -c "JSONObject: { name: string, age: string }"'

export type Schema = {
JSON: object;

JSONObject: { name: string, age: string };

BaseResponse: {
message: Schema["String"] | null,
status: Schema["Boolean"] | null,
response: Schema["JSON"] | null,
params: Schema["JSON"] | null,
};

String: string;

Boolean: string;

BaseList: {
count: Schema["Int"] | null,
next: Schema["String"] | null,
previous: Schema["String"] | null,
results: (Schema["BaseName"] | null)[] | null,
status: Schema["Boolean"] | null,
message: Schema["String"] | null,
};

Int: number;

Ability: {
ability: Schema["BaseName"] | null,
is_hidden: Schema["Boolean"] | null,
slot: Schema["Int"] | null,
};

GameIndex: {
game_index: Schema["Int"] | null,
version: Schema["BaseName"] | null,
};

VersionDetail: {
rarity: Schema["Int"] | null,
version: Schema["BaseName"] | null,
};

HeldItem: {
item: Schema["BaseName"] | null,
version_details: (Schema["VersionDetail"] | null)[] | null,
};

VersionGroupDetail: {
level_learned_at: Schema["Int"] | null,
move_learn_method: Schema["BaseName"] | null,
version_group: Schema["BaseName"] | null,
};

Move: {
move: Schema["BaseName"] | null,
version_group_details: (Schema["VersionGroupDetail"] | null)[] | null,
};

Sprite: {
back_default: Schema["String"] | null,
back_female: Schema["String"] | null,
back_shiny: Schema["String"] | null,
back_shiny_female: Schema["String"] | null,
front_default: Schema["String"] | null,
front_female: Schema["String"] | null,
front_shiny: Schema["String"] | null,
front_shiny_female: Schema["String"] | null,
};

Stat: {
base_stat: Schema["Int"] | null,
effort: Schema["Int"] | null,
stat: Schema["BaseName"] | null,
};

Type: {
slot: Schema["Int"] | null,
type: Schema["BaseName"] | null,
};

BaseName: {
id: Schema["Int"] | null,
url: Schema["String"] | null,
name: Schema["String"] | null,
};

Pokemon: {
abilities: (Schema["Ability"] | null)[] | null,
base_experience: Schema["Int"] | null,
forms: (Schema["BaseName"] | null)[] | null,
game_indices: (Schema["GameIndex"] | null)[] | null,
height: Schema["Int"] | null,
held_items: (Schema["HeldItem"] | null)[] | null,
id: Schema["Int"] | null,
is_default: Schema["Boolean"] | null,
location_area_encounters: Schema["String"] | null,
moves: (Schema["Move"] | null)[] | null,
name: Schema["String"] | null,
order: Schema["Int"] | null,
species: Schema["BaseName"] | null,
sprites: Schema["Sprite"] | null,
stats: (Schema["Stat"] | null)[] | null,
types: (Schema["Type"] | null)[] | null,
weight: Schema["Int"] | null,
status: Schema["Boolean"] | null,
message: Schema["String"] | null,
};

PokemonItem: {
id: Schema["Int"] | null,
url: Schema["String"] | null,
name: Schema["String"] | null,
image: Schema["String"] | null,
artwork: Schema["String"] | null,
dreamworld: Schema["String"] | null,
};

PokemonList: {
count: Schema["Int"] | null,
next: Schema["String"] | null,
previous: Schema["String"] | null,
nextOffset: Schema["Int"] | null,
prevOffset: Schema["Int"] | null,
params: Schema["JSON"] | null,
results: (Schema["PokemonItem"] | null)[] | null,
status: Schema["Boolean"] | null,
message: Schema["String"] | null,
};

Query: {
abilities: Schema["BaseList"] | null,
ability: [{
ability: Schema["String"],
},
Schema["BaseResponse"] | null
],
berries: Schema["BaseList"] | null,
berry: [{
berry: Schema["String"],
},
Schema["BaseResponse"] | null
],
eggGroups: Schema["BaseList"] | null,
eggGroup: [{
eggGroup: Schema["String"],
},
Schema["BaseResponse"] | null
],
encounterMethods: Schema["BaseList"] | null,
encounterMethod: [{
encounterMethod: Schema["String"],
},
Schema["BaseResponse"] | null
],
evolutionChains: Schema["BaseList"] | null,
evolutionChain: [{
id: Schema["String"],
},
Schema["BaseResponse"] | null
],
evolutionTriggers: Schema["BaseList"] | null,
evolutionTrigger: [{
name: Schema["String"],
},
Schema["BaseResponse"] | null
],
genders: Schema["BaseList"] | null,
gender: [{
gender: Schema["String"],
},
Schema["BaseResponse"] | null
],
growthRates: Schema["BaseList"] | null,
growthRate: [{
growthRate: Schema["String"],
},
Schema["BaseResponse"] | null
],
locations: Schema["BaseList"] | null,
location: [{
location: Schema["String"],
},
Schema["BaseResponse"] | null
],
moves: Schema["BaseList"] | null,
move: [{
move: Schema["String"],
},
Schema["BaseResponse"] | null
],
natures: Schema["BaseList"] | null,
nature: [{
nature: Schema["String"],
},
Schema["BaseResponse"] | null
],
pokemons: [{
limit: Schema["Int"] | null,
offset: Schema["Int"] | null,
},
Schema["PokemonList"] | null
],
pokemon: [{
name: Schema["String"],
},
Schema["Pokemon"] | null
],
regions: Schema["BaseList"] | null,
region: [{
region: Schema["String"],
},
Schema["BaseResponse"] | null
],
species: Schema["BaseList"] | null,
types: Schema["BaseList"] | null,
};

CacheControlScope: {
PUBLIC: "PUBLIC",
PRIVATE: "PRIVATE",
};

Upload: any;

}